// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-5q8vOAXB42iXxK5BvNqDqTN17WA5TuQ',
    appId: '1:976106218961:web:a54487dd3a209f7b34ecf0',
    messagingSenderId: '976106218961',
    projectId: 'my-play-on-id',
    authDomain: 'my-play-on-id.firebaseapp.com',
    storageBucket: 'my-play-on-id.firebasestorage.app',
    measurementId: 'G-2V5Q28X8GS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEP0N7S_HWwtraqJaJjSX4aKW4IHEDDy0',
    appId: '1:976106218961:android:73b5fc745e3e7d0234ecf0',
    messagingSenderId: '976106218961',
    projectId: 'my-play-on-id',
    storageBucket: 'my-play-on-id.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4dTNCdI1BWGF6_z4VEtbJeNPcQAxHBzc',
    appId: '1:976106218961:ios:f7e9d64ae417e3fc34ecf0',
    messagingSenderId: '976106218961',
    projectId: 'my-play-on-id',
    storageBucket: 'my-play-on-id.firebasestorage.app',
    iosBundleId: 'com.example.s860126FlutterBasics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4dTNCdI1BWGF6_z4VEtbJeNPcQAxHBzc',
    appId: '1:976106218961:ios:f7e9d64ae417e3fc34ecf0',
    messagingSenderId: '976106218961',
    projectId: 'my-play-on-id',
    storageBucket: 'my-play-on-id.firebasestorage.app',
    iosBundleId: 'com.example.s860126FlutterBasics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-5q8vOAXB42iXxK5BvNqDqTN17WA5TuQ',
    appId: '1:976106218961:web:ba0153e2ad8dfc3434ecf0',
    messagingSenderId: '976106218961',
    projectId: 'my-play-on-id',
    authDomain: 'my-play-on-id.firebaseapp.com',
    storageBucket: 'my-play-on-id.firebasestorage.app',
    measurementId: 'G-X56GL1N086',
  );
}
